language: node_js
node_js:
 - "8"
env:
  secure: Cxycm98UqGetBaFvU7PwTbrdV7FHPUmUSZO8z4e0te3+J13PJBnNO/fysOlvXhDeM4GN3CeBjcOaKIQGhxJHv/h7b0h7/qwwYrU0leatc9FETagP7EJmFaSYne3SN7D8nJQ3LePmO1TtkFkBZw35anz8Sa75ihupR9wV6ruvFvw=

before_deploy:
- openssl aes-256-cbc -K $encrypted_d58e3837dba5_key -iv $encrypted_d58e3837dba5_iv -in xcsoar-data-repository_rsa.enc -out xcsoar-data-repository_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/xcsoar-data-repository_rsa
- ssh-add $TRAVIS_BUILD_DIR/xcsoar-data-repository_rsa
- npm run convert

deploy:
  provider: script
  skip_cleanup: true
  script: ssh-keyscan -p ${DEPLOY_PORT} ${DEPLOY_HOST} > ~/.ssh/known_hosts && scp -P ${DEPLOY_PORT} $TRAVIS_BUILD_DIR/repository ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_PATH}
  on:
    branch: master

notifications:
  irc: 
    channels: 
      - chat.freenode.net#xcsoar
    on_success: change 
    on_failure: always
    template:
       - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{commit_subject}:  %{message}"
       - "Change view : %{compare_url}"
       - "Build details : %{build_url}"
